system:
    EventLoop: feed
    EventLoopThrottle: 0.16 # secs
    network:
        ssl:
            CertFile: /usr/local/etc/openssl/cert.pem

orders:
    ActiveDepth: 10

venues:
    cosine.venues.bem:
        Username: polkadot
        Password: raptor
        APIDomain: https://api-tst.blockex.com/
        APIID: 7c11fb8e-f744-47ee-aec2-9da5eb83ad84
        ConnectSignalR: true

instruments:
#- "XTN/EUR"
- "RCC/EUR"
#- "ETH4/EUR"

feeds:
    cosine.pricing.cryptocompare:
        type: stream
        endpoint: https://streamer.cryptocompare.com
        port: 443
        framework: socket.io
        triangulator: https://min-api.cryptocompare.com
        triangulator_throttle: 0.4 # secs
        instruments:
#            "XTN/EUR":
#                Ticker: "BTC"
            "RCC/EUR":
                BaseCCY: "ETH"
#            "ETH4/EUR":
#                Ticker: "ETH"
feed:
    Primary: cosine.pricing.cryptocompare

pricers:
    Default: cosine.pricing.pricers.nullpricer
    settings:
        cosine.pricing.pricers.nullpricer:
            Nop: nop

strategy:
    type: cosine.strategies.noddy_floater
    settings:
        cosine.strategies.noddy_floater:
            Spread: 0.20
            TopSpread: 0.5
            MaxSpread: 2.5
            StepMaxVar: 0.03
            instrument_settings:
#                "XTN/EUR":
#                    MinVol: 0.001
#                    MaxVol: 0.2
                "RCC/EUR":
                    MinVol: 5
                    MaxVol: 10
#                "ETH4/EUR":
#                    MinVol: 0.0001
#                    MaxVol: 0.2
